### ISSUE TITLE
Questions about running the knn graph code

### ISSUE THREAD

**Issue by HelloWorldLTY** [chenhcs/GIANT#1]
Hi, I tried to run this code:
python coexpression_knn_graph.py --K 10 --datatype "rna" --datadir "path/to/h5ad" --genescopefile "path/to/gene_scope" --outdir "path/to/out_dir"
But found this error:
error: argument --datatype: invalid int value: 'rna'

Could you please help me resolve it? Thanks a lot.

**Comment by HelloWorldLTY** [comment]
I also wonder how to draw these beautiful figures. Many thanks for your help!
![image](https://user-images.githubusercontent.com/43333475/183311583-6bb22726-958d-420a-a096-4b6d1cd4dc58.png)

**Comment by chenhcs** [comment]
The entire repo was updated with an example, please check the latest version of the code. The Sankey figures can be drawn with Plotly (https://plotly.com/python/).
