### ISSUE TITLE
Some questions about differential genes finding and dendrogram drawing

### ISSUE THREAD

**Issue by HelloWorldLTY** [chenhcs/GIANT#2]
Hi, I also find a strange part in the code related to dendrogram drawing:
![image](https://user-images.githubusercontent.com/43333475/183779724-eb50a8b0-8959-4de0-b77c-08218e429375.png)
It seems that the variable group_markers appears without definition, and I think we also did not record the differential genes in different clusters. Could you please share your ideas about how to find it? Thanks a lot!

**Comment by chenhcs** [comment]
The entire repo was updated with an example, please check the latest version of the code.

The differential genes in each cell cluster can be computed with scanpy.tl.rank_genes_groups().
