### ISSUE TITLE
Some questions about personal emb data

### ISSUE THREAD

**Issue by HelloWorldLTY** [chenhcs/GIANT#3]
Hi, I tried to use OhmNET in your version to generate embedding for another dataset and I got tmp.emb file.

Is it the same as the file gene.emb in your example data? If it is, I still receive this error:
![image](https://user-images.githubusercontent.com/43333475/184552904-6c0ab8e2-34ad-405f-8c05-e8dadd285354.png)
Do you have any ideas? Thanks a lot!

**Comment by chenhcs** [comment]
Please use leaf_vectors.emb.

**Comment by HelloWorldLTY** [comment]
Thanks for your comments. I think maybe this problem coming from the leaf_vectors itsef.
![image](https://user-images.githubusercontent.com/43333475/184559422-cee0981a-5e7f-4027-bd22-8e265eba89ff.png)
It seems that the number of dimensions will be stored in the embedding file. So I skip the first line of the file.

**Comment by chenhcs** [comment]
For the current version, you need to format the embedding file as the gene.emb in example_data, which skips the first line of leaf_vectors.emb.

**Comment by HelloWorldLTY** [comment]
Great, many thanks for your help!
