### ISSUE TITLE
A question about clustering analysis

### ISSUE THREAD

**Issue by HelloWorldLTY** [chenhcs/GIANT#4]
Hi, after generating the embedding data, i tried the cluster_gene.py code, but received this error:
![image](https://user-images.githubusercontent.com/43333475/186571507-98bd7afe-c87d-4e4a-ace1-b66054798b52.png)
Do we have files with name "__edgelis__"? Thanks.

**Comment by chenhcs** [comment]
You may not be using the latest version of the code, could you please check with the current code?

**Comment by HelloWorldLTY** [comment]
Solved, many thanks for your help!
