### ISSUE TITLE
Some questions about embedding file

### ISSUE THREAD

**Issue by HelloWorldLTY** [chenhcs/GIANT#5]
Hi, sorry to disturb you again. I found that in the smaple gene.emb file, the name of nodes become _+gene name rather than _+gene_id. The later one is number so I think it is impossible to use gene annotation. Therefore, did you perform inverse map from gene id to gene name after getting the embedding file? Thanks a lot.

**Comment by chenhcs** [comment]
Yes, we did inverse mapping. You can run src/analysis/format_emb_file.py to do the reverse mapping.

**Comment by HelloWorldLTY** [comment]
Thanks a lot!
